plugins {
    id 'java-library'
    id 'io.qameta.allure' version '2.12.0'
}

repositories {
    mavenCentral()
}

allure {
    report {
        version.set('2.19.0')
    }
    adapter {
        aspectjWeaver.set(true)
        frameworks {
            junit5 {
                adapterVersion.set('2.19.0')
            }
        }
    }

    dependencies {
        testImplementation platform('org.junit:junit-bom:6.0.0')
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testImplementation 'com.codeborne:selenide:7.2.2'
        testImplementation 'io.qameta.allure:allure-selenide:2.19.0'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }
}

tasks.withType(Test) {
    useJUnitPlatform()

    testLogging {
        lifecycle {
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }
}
